name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  linux:
    name: Linux (${{ matrix.arch }})
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86
          - arch: x64

    steps:
      - name: Dependencies (x86)
        if: matrix.arch == 'x86'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install g++-multilib libx11-dev:i386 libxext-dev:i386 libxrandr-dev:i386 libxi-dev:i386 libxinerama-dev:i386 libxcursor-dev:i386

      - name: Dependencies (x64)
        if: matrix.arch == 'x64'
        run: |
          sudo apt update
          sudo apt install libx11-dev libxext-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev

      - name: Clone
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: out/build/linux-${{ matrix.arch }}-debug
          key: linux-${{ matrix.arch }}-debug-cmake-v1

      - name: Configure
        run: cmake --preset linux-${{ matrix.arch }}-debug

      - name: Build
        run: cmake --build --preset linux-${{ matrix.arch }}-debug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arcanum-ce-linux-${{ matrix.arch }}
          path:  out/build/linux-${{ matrix.arch }}-debug/arcanum-ce
          retention-days: 7

  windows:
    name: Windows (${{ matrix.arch }})
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86
          - arch: x64

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: out/build/windows-${{ matrix.arch }}
          key: windows-${{ matrix.arch }}-cmake-v1

      - name: Configure
        run: cmake --preset windows-${{ matrix.arch }}

      - name: Build
        run: cmake --build --preset windows-${{ matrix.arch }}-debug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arcanum-ce-windows-${{ matrix.arch }}
          path:  out/build/windows-${{ matrix.arch }}/Debug/arcanum-ce.exe
          retention-days: 7
